services:
  - type: web
    name: pascal-docx-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
      - key: OPENAI_API_BASE
        value: "https://api.openai.com/v1"
      - key: DEBUG
        value: false
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: CORS_ORIGINS
        value: "https://your-frontend-url.com" # Change this to your frontend's URL

  - type: web
    name: pascal-docx-frontend
    env: node
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_VERSION
        value: 20.15.1
      - key: VITE_API_URL
        fromService:
          type: web
          name: pascal-docx-backend
          property: host
